//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseCase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.Issues = new HashSet<Issue>();
            this.People = new HashSet<Person>();
            this.People1 = new HashSet<Person>();
        }
    
        public int locationId { get; set; }
        public string locationName { get; set; }
        public string description { get; set; }
        public string flatNumber { get; set; }
        public int roomNumber { get; set; }
        public string door { get; set; }
        public int floor { get; set; }
    
        public virtual ICollection<Issue> Issues { get; set; }
        public virtual ICollection<Person> People { get; set; }
        public virtual ICollection<Person> People1 { get; set; }
    }
}
