//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseCase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solution
    {
        public string solutionName { get; set; }
        public string explanation { get; set; }
        public System.DateTime decisionTime { get; set; }
        public System.DateTime targetSchedule { get; set; }
        public int issueID { get; set; }
        public int statusID { get; set; }
    
        public virtual Issue Issue { get; set; }
        public virtual Status Status { get; set; }
    }
}
