//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseCase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public Status()
        {
            this.Issues = new HashSet<Issue>();
            this.Solutions = new HashSet<Solution>();
        }
    
        public int statusId { get; set; }
        public string status1 { get; set; }
        public string explanation { get; set; }
    
        public virtual ICollection<Issue> Issues { get; set; }
        public virtual ICollection<Solution> Solutions { get; set; }
    }
}
